# =============================================
# SDMS - AUTHENTICATION API TESTING
# =============================================

@host = http://localhost:8080

### 1. LOGIN
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "staff01",
  "password": "123456"
}

### 2. REFRESH TOKEN
POST {{host}}/api/v1/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": ""
}

### 3. FORGOT PASSWORD
POST {{host}}/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "quoctinh1911@gmail.com"
}

### 4. RESET PASSWORD
POST {{host}}/api/v1/auth/reset-password
Content-Type: application/json

{
  "token": "",
  "newPassword": "NewPassword123@"
}

### 5. LOGOUT
POST {{host}}/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer

{
  "refreshToken": ""
}