export { adminRegistrationApi, studentRegistrationApi } from './registration-api';
export { default as axiosClient } from './axios-client';
export { default as authApi } from './auth-api';
export { default as applicationApi } from './application-api';
export { default as documentApi } from './document-api';
export { default as faceApi } from './face-api';
export { default as roomApi } from './room-api';
export * from './smart-access-api';
export { default as paymentApi } from './payment-api';
export { changeRoomApi } from './change-room-api';
