ALTER TABLE rooms ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 0;
ALTER TABLE dormitory_applications ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 0;
