### 1. Đăng nhập với tư cách SINH VIÊN để lấy Token
# @name studentLogin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "dh52201580@student.stu.edu.vn",
  "password": "Qt@12345678"
}



### 2. Sinh viên Upload ảnh khuôn mặt
# @name uploadFace
POST http://localhost:8080/api/v1/students/me/face
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJESDUyMjAxNTgwIiwiYWNjb3VudElkIjoiZWI2ZDU4NzYtOTRlNS00NTAxLWJkMzEtNjg1ZWFlZTkzZTZlIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3ODUyNDIzNjgsImV4cCI6MTc4NTI0MzI2OH0.JNLnzCkfgiWt0SLeKApaPJuNeczPn-fFcvHBu16McYe9f0u50OYC3mhsKLYrYZddZTlTx0vQjPvz9qzJLKODag
Content-Type: multipart/form-data; boundary=boundary12345

--boundary12345
Content-Disposition: form-data; name="file"; filename="daa6c5f4f77d76232f6c.jpg"
Content-Type: image/jpeg

< C:\Users\DELL\Downloads\daa6c5f4f77d76232f6c.jpg
--boundary12345--

> {%
    // Lưu tự động profileId (UUID) vào biến để lát Admin duyệt
    client.global.set("profile_id", response.body.data);
%}



